Lesson2
andrejdolgovcps/mccme_python_tasks pull request #2
Opened 2020-07-15 11:30 UTC by andrejdolgovcps

Lesson 2 on rewiew.

2020-07-15 11:31 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +
Сделай через рекурсию

2020-07-18 05:10 UTC, sergeychaikacps requested changes

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +    print(0)
Попробуй сделать ещё двумя способами:
1. тернарным оператором
2. https://habr.com/ru/post/495168/

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +    n *= i
Попробуй через рекурсию

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +print(int('179' * 50) ** 2)
Почему не произошло переполнение?

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +a, b, c = [int(i) for i in input().split(',')]
идеально!

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +        print(c)
Попробуй в виде тернарного оператора

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +print("YES" if a + b + c > 2 * d else "NO")
Лучше сразу приучиться оформлять строки одними и теми же кавычками. Советую, как в 96 строчке

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +d = max(a, b, c)
Нужно выносить расчёт в отдельную переменную только в следующих случаях:
1. переменная является глобальным параметром
2. переменная используется в нескольких местах
3. расчёт переменной занимает много места в исходном коде

Переменная d не относятся ни к одному из этих пунктов

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +a = int(pow(179, 10))
Как ещё можно возвести 179 в 10 степень?

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +a = int(pow(179, 10))
Преобразование в тип int округляет всегда вниз. Для округления лучше пользоваться round или связкой round + int

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +print(pow(b, 0.1))
Оператор возведения в степень работает быстрее, чем функция возведения в степень

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +print("YES" if (row2 - row1, col2 - col1) in horse_steps else "NO")
В алгоритме есть ошибка. Если пользователь укажет (0, 0, -2, -1), то программа должна выдать сообщение об ошибке. Необходима проверка на дурака

2020-07-18 05:10 UTC, sergeychaikacps commented on lesson2_tasks_solutions.py
> +print("YES" if (row2 - row1, col2 - col1) in horse_steps else "NO")
Есть предложение. Можно сделать так:
```
horse_shift = (abs(row2 - row1), abs(col2 - col1))
print('YES') if horse_shift == (1, 2) or horse_shift == (2, 1) else print('NO')
```

2020-07-21 20:43 UTC, andrejdolgovcps commented
Add Task 3.

2020-07-21 20:44 UTC, merged