add lesson2
andrejdolgovcps/mccme_python_tasks pull request #4
Opened 2020-07-22 19:50 UTC by andrejdolgovcps

add lesson2

2020-07-23 06:20 UTC, sergeychaikacps requested changes
Давай произведём необходимые изменения и только после того, как я заапрувлю ревью, замержим

2020-07-23 06:20 UTC, sergeychaikacps commented on lesson2_Tasks_solutions.py
> +    n *= i
Добавь решение через рекурсию

2020-07-23 06:20 UTC, sergeychaikacps commented on lesson2_Tasks_solutions.py
> +        print(c)
Вложенные ветвления давай сделаем в одну строку

2020-07-23 06:20 UTC, sergeychaikacps commented on lesson2_Tasks_solutions.py
> +print("YES" if a + b + c > 2 * d else "NO")
Давай строки везде будем или в двойные кавычки оборачивать, или везде в одинарные, а не миксовать

2020-07-23 06:20 UTC, sergeychaikacps commented on lesson2_Tasks_solutions.py
> +print(pow(b, 0.1))
Давай решим в одну строку

2020-07-23 06:20 UTC, sergeychaikacps commented on lesson2_Tasks_solutions.py
> +print("YES" if (row2 - row1, col2 - col1) in horse_steps else "NO")
Попробуй сделать так:
```
horse_shift = (abs(row2 - row1), abs(col2 - col1))
print('YES') if horse_shift == (1, 2) or horse_shift == (2, 1) else print('NO')
```

И давай добавим проверку на выход за границы доски

2020-07-29 21:31 UTC, andrejdolgovcps commented on lesson2_Tasks_solutions.py
> +print("YES" if (row2 - row1, col2 - col1) in horse_steps else "NO")
эту задачу не успел доделаю завтра и приступлю к правкам по задачам 3

2020-07-30 03:25 UTC, sergeychaikacps commented on lesson2_Tasks_solutions.py
> +print("YES" if (row2 - row1, col2 - col1) in horse_steps else "NO")
Принято

2020-08-01 10:28 UTC, sergeychaikacps approved these changes
В задаче N необходимо также проверять на положительность входных значений

2020-08-01 10:29 UTC, merged